queue_rules:
    - name: default
      merge_conditions:
          - check-success=buildbot/nix-build
      merge_method: rebase

pull_request_rules:
    - name: Queue
      conditions:
          - base=main
          - label~=merge-queue|dependencies
      actions:
          queue:
