keys:
  users:
    - &akos DC6C238558CF0FC39400BA2EE2256EAE7390AF2C
  hosts:
    - &athena age1nmfkvqnclhdr4j4ev7yug8ehrsl8hh09tuffmks0dfl8w4dkqv5sqhf3u4
    - &kratos age1vlxveywlyww4zymyxmd8y4mjg2dxeev6a3vdw4v7qvekcpgnc3asu2xvcu
    - &zeus age16kd99x3lsmq9tfxn42zr9npdtjtw8y68stykm6apjkt9gexwsdssmd3sjz
    - &gaia age1gqdrkenwc3dwk384285gtz0zzgfl2c55xklx2hvhr8c6h4duggyqwmy2w7
    - &uranus age1us58kmzzemu8ns8t2dm7y97dhwsxatqf8gnz573zwhqjhx43uurqvlwypz
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *athena
          - *kratos
          - *zeus
          - *gaia
          - *uranus
        pgp:
          - *akos
  - path_regex: home/akos/secrets.ya?ml$
    key_groups:
      - pgp:
          - *akos
  - path_regex: hosts/gaia/secrets.ya?ml$
    key_groups:
      - age:
          - *gaia
        pgp:
          - *akos
  - path_regex: hosts/gaia/home-assistant/secrets.ya?ml$
    key_groups:
      - age:
          - *gaia
        pgp:
          - *akos
  - path_regex: hosts/zeus/secrets.ya?ml$
    key_groups:
      - age:
          - *zeus
        pgp:
          - *akos
