keys:
  - &users:
    - &akos DC6C238558CF0FC39400BA2EE2256EAE7390AF2C
  - &hosts:
    - &athena age1nmfkvqnclhdr4j4ev7yug8ehrsl8hh09tuffmks0dfl8w4dkqv5sqhf3u4
    - &kratos age1n8mcwnl4pwdkdlxntndgqnc6p6cuqltv97tpvy2xwlsv2x5y0qeqlk4ych

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
        - *athena
        - *kratos
        pgp:
        - *akos
