keys:
  users:
    - &akos DC6C238558CF0FC39400BA2EE2256EAE7390AF2C
  hosts:
    - &athena age1nmfkvqnclhdr4j4ev7yug8ehrsl8hh09tuffmks0dfl8w4dkqv5sqhf3u4
    - &kratos age1vlxveywlyww4zymyxmd8y4mjg2dxeev6a3vdw4v7qvekcpgnc3asu2xvcu
    - &gaia age1gqdrkenwc3dwk384285gtz0zzgfl2c55xklx2hvhr8c6h4duggyqwmy2w7
    - &uranus age1us58kmzzemu8ns8t2dm7y97dhwsxatqf8gnz573zwhqjhx43uurqvlwypz
    - &hyperion age1qq68007k0v2tl4qwfvwhaxpp4lskaccallrmzsv7w3lhwpae635qckaykc
    - &ceyx age1kd9kp2twvyskq0rte588s7tfvzcw62dh0xwftcaqdj2vdpxqyddq869u6s
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *athena
          - *kratos
          - *gaia
          - *uranus
          - *hyperion
          - *ceyx
        pgp:
          - *akos
  - path_regex: home/akos/secrets.ya?ml$
    key_groups:
      - pgp:
          - *akos
  - path_regex: hosts/gaia/secrets.ya?ml$
    key_groups:
      - age:
          - *gaia
        pgp:
          - *akos
  - path_regex: hosts/gaia/home-assistant/secrets.ya?ml$
    key_groups:
      - age:
          - *gaia
        pgp:
          - *akos
  - path_regex: hosts/uranus/secrets.ya?ml$
    key_groups:
      - age:
          - *uranus
        pgp:
          - *akos
  - path_regex: hosts/hyperion/secrets.ya?ml$
    key_groups:
      - age:
          - *hyperion
        pgp:
          - *akos
  - path_regex: hosts/ceyx/secrets.ya?ml$
    key_groups:
      - age:
          - *ceyx
        pgp:
          - *akos
