{
	"data": "ENC[AES256_GCM,data:kehRvwhGtilB2UFH581c10P10X8GQAWnZ7BwDpqEAqXAXHVKIboB1EFNiCfc0J7FQgOV2GlDq2upTAm9/3vnNW4ekemeDzoqnHLjaS13swjNey1GfT5/Sn9nmDlIzo1636ocjsFoFHH7tC1yi1edDOAXXn4r4GnFQheh,iv:1rKe5sdys4qm1D9jscVWgP2WIE1B5k1hrba8xxqJeSA=,tag:roimcMZovmxZ2cp1G7bSWw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWUFEQ0ZBR0RYMENXRlZO\naG5sek1nVDZYaVpiQ1Y3cFdVZWhwQUtQZ25FCnEySDRUYjJMOXVYUTV5ejdhSFQz\naDdBcldSakZsdHZIeUZOajBOVXp5Z2cKLS0tIGRYa1EwR1plb2FsWXVkQnljRGw3\nRmxjb3ZmU3hCOEtsdWVXbnVBYlRVVkkK11g910cXLgw/Vul0cMJWerPnB0OYAspX\nHPpaJNFiDIo1f2UYvJ10ctXKG1jADsz9OOqAd4SHpCT1bMq4CG737Q==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1qq68007k0v2tl4qwfvwhaxpp4lskaccallrmzsv7w3lhwpae635qckaykc"
			}
		],
		"lastmodified": "2026-09-03T15:37:19Z",
		"mac": "ENC[AES256_GCM,data:2DZjN8qeoiyfx6yjiTGYaDW+vkdBsPVojdYqbMoNGT8CblzlcmMZDM3uFn10g3GkHgQ+UhZpoagaBsFs4dRoc8RPrGx271mY4WOlHzbdikb6GZe0ZY7drCyUo/3jYQFq7jKiwwI1Ff87RHpAra+0VXzAXBr0ImR848GmA9BNLOw=,iv:JhElEWpmnB8L9InhYG9a33wPvnSTirWIloWi0kmAlHw=,tag:IrT/gh7Nwnh+MOEnaWSUpQ==,type:str]",
		"pgp": [
			{
				"created_at": "2026-04-04T14:14:56Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhF4DAPfT6sZVG+sSAQdAeHRdRVxtsELi3509gOaZnP03GHRmHS0gnYMGjBYqIQ8w\nvJhDIcrtIHC9YDNMxQsVaJxukKHz0n8rcR92xZvp6dqJTQDF3sA9e9+S+4UI8Oz8\n0l4B7aCjSoCjctvmgJCnNZUxXnx5qE2pG+6e/kqfk8uvcnOLBdXJI+954fIcNf/B\nn1oF6DlYvPjkhfgt267Mj+e9ld20fupbOCmZa/YwJSBHU0HdZHn7AeouKtf/4787\n=AkH/\n-----END PGP MESSAGE-----",
				"fp": "73CF708E26789E613672C40D236F3ED93EDDCDEF"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.12.1"
	}
}
