{
	"data": "ENC[AES256_GCM,data:yGBfzvvDz5+7eZLzb1NBwI90TnCsrmduenr/x276Yq8asWZ2TX1sXTZi+oJ8hsXdIHCvogo8ClfWRp6eYT4LZ3vzjlttubMmdXlkbeRlAKUqWshZr5Cw4yc4S78NZZPCYFeI3Fod80AFGzP1BLes8OdiHzPDc36os51s,iv:1rKe5sdys4qm1D9jscVWgP2WIE1B5k1hrba8xxqJeSA=,tag:WZhJIQUUzIcN3fs7op78pA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1qq68007k0v2tl4qwfvwhaxpp4lskaccallrmzsv7w3lhwpae635qckaykc",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVhNZWkrT240cmlWYjFL\nL0xneGdNekI3eFh4VnlwemErSVUwaWhELzBnCjArK2FUN3lyODhwdzNBSUY5SlQ1\nNmVpalNqdVpVaXRLTjhqM3NjNnJkNW8KLS0tIDE1RWNueE1yNHV4dEVObW1CSnlJ\nUGdoWDg5M1VrV0ZQUDkyZWp3MDdzeE0Kk6secij0/MH3WnxPIo1F/SO4xA89EEJQ\nTYWRsiVFObibJ2UNbbVS4Z+l7ARUam2PnRjljtQc9a5xNh+YZ3FepA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-04T14:15:46Z",
		"mac": "ENC[AES256_GCM,data:PB4iiLC0d+HQqOKg1QfsEwhTi28BnMhljz753GHp5KPHy8ZtZNisuC/S5Wvxrm4lekCzvsvUq5PdIYsy/fGWwYiDtr6ypPVw40Uzjc3BlypmExWBC8LQe3UevuvdclH4beDRbZbqEXu0xq7/oO/B7wApzvsEtgISVejPoDbAB4Y=,iv:Lw53VwVuM4ZQrtu7XEXEhrDTDpjK8dQtaS7FJBZNJqU=,tag:e/YRp2hufmHZXXJG9G3bvw==,type:str]",
		"pgp": [
			{
				"created_at": "2026-04-04T14:14:56Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhF4DGRnCPPu8bPcSAQdAmFajFL/3AMYIVFvt6hR07rxGUVQDYmQpT2kKBfT3Ki0w\nl58lKjO5fi8/oua9xSEh8LNwQxxY0hyAhiXLL/Af4exkeH75B8FVw/5SADBClloO\n0l4BjLr8mhujmPcmLZt60qvonNtraRJXIBWXC2CopnFleZTRwCKYvzC//N6+to6t\n0Q5/CU9lOG2M27LCt6AY82wSzon4mRxvtkLNHD+Rh/GqewUGNDgjXKvHOte+sWIP\n=OI43\n-----END PGP MESSAGE-----",
				"fp": "73CF708E26789E613672C40D236F3ED93EDDCDEF"
			}
		],
		"version": "3.12.1"
	}
}
