category_limits:
  - name: Redacted
    seeding_time_limit: -1
    ratio_limit: 0.6
  - name: nCore
    seeding_time_limit: 3240
    ratio_limit: 1.01
  - name: nCore Sorozatok
    seeding_time_limit: 3240
    ratio_limit: 1.01
  - name: nCore Filmek
    seeding_time_limit: 3240
    ratio_limit: 1.01
  - name: TorrentLeech
    seeding_time_limit: 14450
    ratio_limit: 1
  - name: RuTracker
    seeding_time_limit: 14450
    ratio_limit: 0.6
  - name: BestCore
    seeding_time_limit: 4350
    ratio_limit: 0.8
  - name: ProAudioTorrents
    seeding_time_limit: -1
    ratio_limit: -1
  - name: Bitmagnet
    seeding_time_limit: 0
    ratio_limit: 0

